name: deploy

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            ./build/
          key: build-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: build-cargo-

      - run: cargo run -- -publish

      - uses: actions/upload-pages-artifact@v1.0.4
        name: Upload static assets
        with:
          path: ./output/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
